name = "example"
compatibility_date = "2022-05-15"
main = "dist/index.js"

kv_namespaces = [
  { binding = "KV", id = "", preview_id = ""}
]

[build.upload]
format = "modules"
dir = "dist"
main = "./index.js"

[miniflare]
host = "localhost"
port = 80